### ISSUE TITLE
Send logs to an IRC channel to monitor if there's an error (rate limit for example)

### ISSUE THREAD

**Issue by Seluj78** [AFPy/PyDocTeur#13]

**Comment by JulienPalard** [comment]
An easy way would be to use `irker` to persist the IRC connexion for us, it's packaged on Debian, it's a daemon that connects to IRC and provide a simple API:

It listens UDP or TCP packets on port 6659 and expects one-line jsons containing `to` and `privmsg`, that's it.

Some examples from the manpage:

       {"to":"irc://chat.freenode.net/git-ciabot", "privmsg":"Hello, world!"}
       {"to":["irc://chat.freenode.net/#git-ciabot","irc://chat.freenode.net/#gpsd"],"privmsg":"Multichannel test"}
       {"to":"irc://chat.hypothetical.net:6668/git-ciabot", "privmsg":"Hello, world!"}
       {"to":"ircs://chat.hypothetical.net/git-private?key=topsecret", "privmsg":"Keyed channel test"}
       {"to":"ircs://:topsecret@chat.example.net/git-private", "privmsg":"Password-protected server test"}

In Python, it's as simple as:

```python
with socket.socket(type=socket.SOCK_DGRAM) as irc:
    irc.sendto(b'{"to":"irc://chat.freenode.net/mdk", "privmsg":"Hello, world!"}', ('127.0.0.1', 6659))
```

As it expects no response, it's on localhost, and there's no handshake, it fast. like 0.0002s fast. All the slow connexion to IRC is done after, by irkerd.

**Comment by JulienPalard** [comment]
![](https://mdk.fr/x/irker.png?1)

**Comment by Seluj78** [comment]
Niiice ! Is there a channel for it ?

**Comment by JulienPalard** [comment]
#python-docs-fr on freenode.
