### ISSUE TITLE
Handle out of date branches !

### ISSUE THREAD

**Issue by Seluj78** [AFPy/PyDocTeur#18]
![Screenshot 2020-11-29 at 18 01 04](https://user-images.githubusercontent.com/4641317/100548439-dc5ef700-326c-11eb-8b9b-6ca650357d07.png)

**Comment by Seluj78** [comment]
https://pygithub.readthedocs.io/en/latest/github_objects/PullRequest.html#github.PullRequest.PullRequest.mergeable

**Comment by vpoulailleau** [comment]
Cf https://github.com/python/python-docs-fr/pull/1500#issuecomment-744334946

À minima, mettre en attente le merge tant que la branche n'est pas à jour wink

Après, PyDocTeur peut suggérer à l'utilisateur de faire un git pull --rebase suivi d'un git push, mais j'ai peur que ce soit une difficulté pour les personnes pas trop à l'aise avec git.

Éventuellement, PyDocTeur pourrait peut être tenter le rebase en automatique, et s'il se passe bien, merger, sinon laisser en l'état avant le rebase.
