### ISSUE TITLE
PyDocTeur could comment on the PR diff some simple errors like nb spaces ?

### ISSUE THREAD

**Issue by Seluj78** [AFPy/PyDocTeur#27]

**Comment by Seluj78** [comment]
https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#create-a-review-comment-for-a-pull-request

**Comment by Seluj78** [comment]
https://github.com/PyGithub/PyGithub/issues/1803

**Comment by JulienPalard** [comment]
Like I wrote on #59, I don't think this is in the scope of the bot, this should be in workflows.
