### ISSUE TITLE
Same reviewer mentionned several times in message.

### ISSUE THREAD

**Issue by awecx** [AFPy/PyDocTeur#32]
See https://github.com/python/python-docs-fr/pull/1478.
![image](https://user-images.githubusercontent.com/43954001/100632008-9e290c80-332c-11eb-8e45-b877e9193062.png)

A bit puzzling thought, https://github.com/AFPy/PyDocTeur/blob/main/pydocteur/utils/state_actions.py#L42 looks good to me.

**Comment by Seluj78** [comment]
That's what I thought too ! i'll check on it

**Comment by Seluj78** [comment]
```python
>>> {i for i in ["awecx", "awecx", "awecx"]}
{'awecx'}
```

**Comment by Seluj78** [comment]
Could not reproduce.

**Comment by Seluj78** [comment]
(@JulienPalard removed some comment states so it's most likely why)
