### ISSUE TITLE
Force wsgi server to use only 1 thread

### ISSUE THREAD

**Issue by Seluj78** [AFPy/PyDocTeur#36]
Rationale: If we use multiple threads in production, then the bot might receive multiple hooks at the same time, process them and comment the same thing multiple twice

**Comment by JulienPalard** [comment]
It's already the case: https://github.com/AFPy/infra/blob/9cc7befb789cf76e9a427d15b52b06f1a2d03c08/pydocteur.afpy.org.yml#L84
