### ISSUE TITLE
Custom commit message/title with nice infos and saying it's auto merged.

### ISSUE THREAD

**Issue by vpoulailleau** [AFPy/PyDocTeur#50]
Super boulot ce PyDocTeur :tada: 

J'ai ressorti un TODO du code :

https://github.com/AFPy/PyDocTeur/blob/d6abb5a785f982587ba5f5fd30ce53fd5b345f35/pydocteur/actions.py#L88-L89

Le message pourrait dire :

```
Automerge of PR #unnombre

Fix #lenumerodissue (si il y en a une)

Co-authored-by: name <name@example.com>
Co-authored-by: another-name <another-name@example.com>

Body d'origine de la PR
```

Qu'en pensez-vous ?

**Comment by vpoulailleau** [comment]
Pour trouver le numéro d'issue, une petite regex basée sur https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references :

En ignorant la casse :

* close
* closes
* closed
* fix
* fixes
* fixed
* resolve
* resolves
* resolved

**Comment by vpoulailleau** [comment]
```python
import re

for pr_body in [
    "Close #1337",
    "Closes #1337",
    "Closed #1337",
    "Fix #1337",
    "Fixes #1337",
    "Fixed #1337",
    "Resolve #1337",
    "Resolves #1337",
    "Resolved #1337",
]:
    issue_number = None
    if m := re.search(
        "(?:close[sd]?|fix|fixe[sd]|resolve[sd]?)\s+(#\d+)",
        pr_body,
        re.IGNORECASE,
    ):
        issue_number = m[1]
    print(issue_number)

```

**Comment by Seluj78** [comment]
Génial ! Je vais regarder pour implementer ça, ou Julien, ou toi si tu le sens !

**Comment by Seluj78** [comment]
Je suis dessus

**Comment by Seluj78** [comment]
https://github.com/PyDocTeur/fake-docs/commit/e77e2451e505dc7607adce1e424d9cc5aa9e6598

**Comment by Seluj78** [comment]
https://github.com/PyDocTeur/fake-docs/commit/62a8902e4d79ad1bfa0234701389b6d6e14ae3bd

**Comment by Seluj78** [comment]
Le co-authored est pas pris en compte on dirais
Est ce que il faut que il soit mis au bon endroit ?

**Comment by vpoulailleau** [comment]
J'en sais pas plus que ça : https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

Ça m'a l'air bon ce que tu as fait. Peut-être qu'il faut mettre les co-authored à la fin ?

**Comment by vpoulailleau** [comment]
Ah si, ça semble être ça :

adding a Co-authored-by: **trailer** to the commit's message.

**Comment by Seluj78** [comment]
Donc faut les mettre à la fin. Ok! @vpoulailleau tu peux ouvrir une fake pr sur `fake-docs` ? Que je fasse des tests

**Comment by vpoulailleau** [comment]
@Seluj78 Et voici : https://github.com/PyDocTeur/fake-docs/pull/18
