### ISSUE TITLE
Does not recognize PR titles which end with .po ?

### ISSUE THREAD

**Issue by christopheNan** [AFPy/PyDocTeur#61]
See PyDocTeur comments in https://github.com/python/python-docs-fr/pull/1544 and https://github.com/python/python-docs-fr/pull/1546

**Comment by vpoulailleau** [comment]
https://github.com/AFPy/PyDocTeur/blob/c45d95e45ee69d797fa1197177fbb714b15eeb45/pydocteur/pr_status.py#L92

Il faut soit supprimer le `r` devant la chaine, soit remplacer `\\` par `\`

**Comment by christopheNan** [comment]
So fast! :smile:

**Comment by Seluj78** [comment]
Normalement c'est deploy (v1.11.1) et fix, a tester. Pour voir la version, c'est dans les commentaires et sur https://pydocteur.afpy.org
