### ISSUE TITLE
Tells the PR title is bad, but don't tell how to fix it

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/PyDocTeur#62]
see https://github.com/python/python-docs-fr/pull/1551

**Comment by vpoulailleau** [comment]
See https://github.com/AFPy/PyDocTeur/blob/94e3d28e2d23bd4ccba26d42fc3c54d999bb515e/pydocteur/pr_status.py#L88 to get the naming rules. I agree that the message can be improved :wink:
