### ISSUE TITLE
Relancer les tests de CI sur un commentaire

### ISSUE THREAD

**Issue by christopheNan** [AFPy/PyDocTeur#66]
Si un commentaire contient "restest this please", PyDocTeur relancerait les tests de CI.

**Comment by christopheNan** [comment]
cf. https://github.com/python/python-docs-fr/pull/1593#issuecomment-822069793

**Comment by JulienPalard** [comment]
J'ignore si c'est possible, cependant fermer et réouvrir une PR relance les tests.

**Comment by Seluj78** [comment]
https://github.com/sindresorhus/refined-github/issues/3113

**Comment by Seluj78** [comment]
https://docs.github.com/en/rest/reference/actions#re-run-a-workflow

**Comment by Seluj78** [comment]
WOOHOO
Ca fonctinne ! J'ai réussi à relancer les tests de https://github.com/python/python-docs-fr/pull/1594 depuis la CLI python avec ceci:

```py
url = "https://api.github.com/repos/python/python-docs-fr/actions/runs/761647205/rerun"
headers = {"Authorization": "Bearer {}".format("XXXXXXXXXXX")}
import requests
resp = requests.post(url, headers=headers)
```
