### ISSUE TITLE
Test results may be wrong

### ISSUE THREAD

**Issue by christopheNan** [AFPy/PyDocTeur#67]
The line https://github.com/AFPy/PyDocTeur/blob/34710c7079e1cf5875acc40b6d93219c6bedf1fb/pydocteur/pr_status.py#L14 checks for last commit tests.
But if the PR was closed and re-opened (for example because the tests crashed), then the tests are re-launched and the result is not detected by PyDocTeur.

**Comment by Seluj78** [comment]
This should be fixed by https://github.com/AFPy/PyDocTeur/pull/68
